scrape_configs:  # Define the list of scrape configurations for Prometheus
  - job_name: 'skyward-app-scrape'  # Name of the scrape job
    scrape_interval: 1s  # How often Prometheus should scrape the metrics endpoint (every 1 second)
    metrics_path: '/actuator/prometheus'  # Path to the metrics endpoint that Prometheus will scrape
    static_configs:  # Define static targets for this scrape job
      - targets: ['skyward-app:8080']  # List of targets (endpoints) to scrape metrics from, in this case, the skyward-app on port 8080
