@startuml
actor User

package "Application" {
  [skyward-app]
}

package "Database" {
  [skyward-database]
}

package "Logging" {
  [skyward-filebeat]
  [skyward-logstash]
  [skyward-elasticsearch]
  [skyward-kibana]
}

package "Metrics" {
  [skyward-prometheus]
  [skyward-grafana]
}

package "Tracing" {
  [skyward-jaeger]
}

User --> [skyward-app] : Uses
[skyward-app] --> [skyward-database] : Database Operations

[skyward-app] --> [skyward-filebeat] : Sends Logs
[skyward-filebeat] --> [skyward-logstash] : Forwards Logs
[skyward-logstash] --> [skyward-elasticsearch] : Sends Processed Logs
[skyward-kibana] --> [skyward-elasticsearch] : Queries Logs
User --> [skyward-kibana] : Views Logs

[skyward-app] --> [skyward-prometheus] : Sends Metrics
[skyward-grafana] --> [skyward-prometheus] : Queries Metrics
User --> [skyward-grafana] : Views Metrics

[skyward-app] --> [skyward-jaeger] : Sends Trace Data
User --> [skyward-jaeger] : Views Traces
@enduml
