@startuml

skinparam componentStyle rectangle

package "Parent Project" {
    [skyward-parent]
}

package "Skyward Modules" {
    [skyward-data] --> [skyward-parent]
    [skyward-tracing] --> [skyward-parent]
    [skyward-server] --> [skyward-parent]
    [skyward-openapi] --> [skyward-parent]

    [skyward-server] --> [skyward-data]
    [skyward-server] --> [skyward-tracing]
    [skyward-server] --> [skyward-openapi]
}

package "Dependencies" {
    package "Common Dependencies" {
        [spring-boot-autoconfigure]
        [spring-boot-configuration-processor]
        [logstash-logback-encoder]
        [logback-classic]
        [spring-ai-ollama-spring-boot-starter]
        [spring-boot-devtools]
        [spring-boot-docker-compose]
        [mysql-connector-j]
        [lombok]
        [spring-boot-starter-test]
        [spring-boot-testcontainers]
        [spring-security-test]
        [testcontainers-junit-jupiter]
        [testcontainers-mysql]
        [jakarta.jakartaee-api]
        [bcprov-jdk15on]
        [bcpkix-jdk15on]
        [bcutil-jdk15on]
        [guava]
        [protobuf-java]
        [commons-compress]
        [spring-ai-bom]
        [spring-boot-dependencies]
        [zipkin-reporter-brave]
        [micrometer-tracing-bridge-brave]
        [micrometer-registry-prometheus]
        [mapstruct]
        [mapstruct-processor]
        [jjwt]
        [spring-security-jwt]
        [opentelemetry-api]
        [opentelemetry-sdk]
        [opentelemetry-extension-annotations]
        [opentelemetry-exporter-otlp]
        [opentelemetry-spring-boot-starter]
        [grpc-netty-shaded]
        [opentelemetry-semconv]
    }

    package "Data Module Dependencies" {
        [spring-boot-starter]
        [spring-boot-starter-data-jpa]
    }

    package "Tracing Module Dependencies" {
        [spring-boot-starter]
        [opentelemetry-api]
        [opentelemetry-sdk]
        [opentelemetry-extension-annotations]
        [opentelemetry-exporter-otlp]
        [opentelemetry-spring-boot-starter]
        [grpc-netty-shaded]
        [micrometer-registry-prometheus]
        [opentelemetry-semconv]
    }

    package "Server Module Dependencies" {
        [spring-boot-starter]
        [spring-boot-loader]
        [spring-boot-starter-web]
        [spring-boot-starter-security]
        [spring-boot-starter-actuator]
        [jjwt]
        [spring-security-jwt]
        [spring-security-oauth2-jose]
        [spring-boot-starter-jersey]
        [spring-boot-starter-undertow]
        [jersey-media-json-jackson]
        [skyward-data]
        [skyward-tracing]
        [skyward-openapi]
        [mapstruct]
        [mapstruct-processor]
        [rest-assured]
    }

    package "OpenAPI Module Dependencies" {
        [jakarta.jakartaee-api]
        [swagger-core]
        [jackson-core]
        [jackson-databind]
        [jackson-annotations]
        [jackson-datatype-jsr310]
        [jackson-databind-nullable]
        [lombok]
    }
}

[skyward-data] -down-> [skyward-parent]
[skyward-tracing] -down-> [skyward-parent]
[skyward-server] -down-> [skyward-parent]
[skyward-openapi] -down-> [skyward-parent]

[skyward-server] -left-> [skyward-data]
[skyward-server] -right-> [skyward-tracing]
[skyward-server] -down-> [skyward-openapi]

[skyward-parent] --> [spring-boot-autoconfigure]
[skyward-parent] --> [spring-boot-configuration-processor]
[skyward-parent] --> [logstash-logback-encoder]
[skyward-parent] --> [logback-classic]
[skyward-parent] --> [spring-ai-ollama-spring-boot-starter]
[skyward-parent] --> [spring-boot-devtools]
[skyward-parent] --> [spring-boot-docker-compose]
[skyward-parent] --> [mysql-connector-j]
[skyward-parent] --> [lombok]
[skyward-parent] --> [spring-boot-starter-test]
[skyward-parent] --> [spring-boot-testcontainers]
[skyward-parent] --> [spring-security-test]
[skyward-parent] --> [testcontainers-junit-jupiter]
[skyward-parent] --> [testcontainers-mysql]
[skyward-parent] --> [jakarta.jakartaee-api]
[skyward-parent] --> [bcprov-jdk15on]
[skyward-parent] --> [bcpkix-jdk15on]
[skyward-parent] --> [bcutil-jdk15on]
[skyward-parent] --> [guava]
[skyward-parent] --> [protobuf-java]
[skyward-parent] --> [commons-compress]
[skyward-parent] --> [spring-ai-bom]
[skyward-parent] --> [spring-boot-dependencies]
[skyward-parent] --> [micrometer-tracing-bridge-brave]
[skyward-parent] --> [micrometer-registry-prometheus]
[skyward-parent] --> [mapstruct]
[skyward-parent] --> [mapstruct-processor]
[skyward-parent] --> [jjwt]
[skyward-parent] --> [spring-security-jwt]
[skyward-parent] --> [opentelemetry-api]
[skyward-parent] --> [opentelemetry-sdk]
[skyward-parent] --> [opentelemetry-extension-annotations]
[skyward-parent] --> [opentelemetry-exporter-otlp]
[skyward-parent] --> [opentelemetry-spring-boot-starter]
[skyward-parent] --> [grpc-netty-shaded]
[skyward-parent] --> [opentelemetry-semconv]

   [skyward-data] --> [spring-boot-starter]
   [skyward-data] --> [spring-boot-starter-data-jpa]

[skyward-tracing] --> [spring-boot-starter]
[skyward-tracing] --> [opentelemetry-api]
[skyward-tracing] --> [opentelemetry-sdk]
[skyward-tracing] --> [opentelemetry-extension-annotations]
[skyward-tracing] --> [opentelemetry-exporter-otlp]
[skyward-tracing] --> [opentelemetry-spring-boot-starter]
[skyward-tracing] --> [grpc-netty-shaded]
[skyward-tracing] --> [micrometer-registry-prometheus]
[skyward-tracing] --> [opentelemetry-semconv]

[skyward-server] --> [spring-boot-starter]
[skyward-server] --> [spring-boot-loader]
[skyward-server] --> [spring-boot-starter-web]
[skyward-server] --> [spring-boot-starter-security]
[skyward-server] --> [spring-boot-starter-actuator]
[skyward-server] --> [jjwt]
[skyward-server] --> [spring-security-jwt]
[skyward-server] --> [spring-security-oauth2-jose]
[skyward-server] --> [spring-boot-starter-jersey]
[skyward-server] --> [spring-boot-starter-undertow]
[skyward-server] --> [jersey-media-json-jackson]
[skyward-server] --> [skyward-data]
[skyward-server] --> [skyward-tracing]
[skyward-server] --> [skyward-openapi]
[skyward-server] --> [mapstruct]
[skyward-server] --> [mapstruct-processor]
[skyward-server] --> [rest-assured]
[skyward-openapi] --> [jakarta.jakartaee-api]
[skyward-openapi] --> [swagger-core]
[skyward-openapi] --> [jackson-core]
[skyward-openapi] --> [jackson-databind]
[skyward-openapi] --> [jackson-annotations]
[skyward-openapi] --> [jackson-datatype-jsr310]
[skyward-openapi] --> [jackson-databind-nullable]
[skyward-openapi] --> [lombok]

@enduml
